global:

scrape_configs:
  - job_name: 'pages'
    scrape_interval: 5s
    scrape_timeout: 10s
    target_groups:
      - targets: ['pages.weave.local:9090']

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 10s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    target_groups:
      - targets: ['localhost:9090']
