global:

scrape_configs:
  - job_name: 'amber'
    scrape_interval: 5s
    scrape_timeout: 10s
    dns_sd_configs:
        - port: 9000
          type: A
          names:
            - 'stats.weave.local'

  - job_name: 'preso'
    scrape_interval: 5s
    scrape_timeout: 10s
    dns_sd_configs:
        - port: 9090
          type: A
          names:
            - 'preso.weave.local'

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 10s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    target_groups:
      - targets: ['localhost:9090']
